config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :articles
  end
  root "categories#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
  @articles = Article.all.sort_by &:created_at
end

def show
  @article = Article.find(params[:id])
end

def new
  @article = Article.new(params[:id])
  @category = Category.find(params[:category_id])
end

def create
  @category = Category.find(params[:category_id])
  @article = @category.articles.new(article_params)
  if @article.save
    redirect_to category_article_path(@category, @article)
  else
    @errors = "Invalid article."
  end
end

def edit
  @category = Category.find(params[:category_id])
  @article = Article.find(params[:id])
end

def update
  @article = Article.find(params[:id])
  if @article.update(article_params)
    redirect_to category_article_path(@article.category, @article)
  else
    @errors = "Try again. Now."
  end
end

def destroy
  @category = Category.find(params[:category_id])
  @article = Article.find(params[:id])
  @article.destroy
  redirect_to category_path(@category)
end

private

  def article_params
    params.require(:article).permit(:title, :description, :price, :email)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
def index
  @categories = Category.all.sort_by &:created_at
end

def show
  @category = Category.find(params[:id])
end

def new
  @category = Category.new(params[:id])
end

def create
  @category = Category.new(category_params)
  if @category.save
    redirect_to @category
  else
    @errors = "Invalid category."
  end
end

def edit
  @category = Category.find(params[:id])
end

def update
  @category = Category.find(params[:id])
  if @category.update(category_params)
    redirect_to @category
  else
    @errors = "Try again. Now."
  end
end

def destroy
  @category = Category.find(params[:id])
  @category.destroy
  redirect_to categories_path
end

private

  def category_params
    params.require(:category).permit(:title)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for [@category, @article] do |f|%>
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.label :price %><br>
  $ <%= f.text_field :price %>
</p>
<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>
 <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h2>Edit <%= @article.title %></h2>

<%=render "form"%>

<footer>

 <%=button_to 'Back', category_articles_path, method: "get"%>

</footer>

app/views/articles/index.html.erb
<h2>All Articles</h2>
<table>
<% @articles.each do |article| %>
<tr>
  <td>
   <%=article.title, article_path(article)%>
 </td>
 <td><%= link_to "Edit", edit_category_article_path(article.category, article)%></td>
  <td><%= button_to "Delete", category_article_path(article.category, article), method: :delete %></td>
 </tr>
<% end %>

app/views/articles/new.html.erb
<h3>New Article</h3>

<%= render "form"%>

<footer>

 <%=button_to 'Back', category_path(@category), method: "get"%>

</footer>

app/views/articles/show.html.erb
<h2><%=@article.title%></h2>
<br>
<b>Description: </b><br>
<%=@article.description%>
<br>
<br>
<b>Price:</b> $<%=@article.price%>
<br>
<br>
<b>Contact:</b> <br>

<%=@article.email%>
<br><br>



<footer>

 <%=button_to 'Back', category_path(@article.category), method: "get"%>

</footer>

app/views/categories/_form.html.erb
<%= form_for @category do |f|%>
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@category.errors.count, "error") %> prohibited
      this category from being saved:
    </h2>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
 <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/categories/edit.html.erb
<h2>Edit <%= @category.title %></h2>


<%= render "form"%>

<footer>

 <%=button_to 'Back', categories_path, method: "get"%>

</footer>

app/views/categories/index.html.erb
<h2 class="first">All Categories</h2>
<table>
<% @categories.each do |category| %>
<tr>
  <td>
   <%= link_to category.title, category_path(category)%>
 </td>
 <td><%= link_to "Edit", edit_category_path(category)%></td>
  <td><%= button_to "Delete", category_path(category), method: :delete %></td>
</tr>
<% end %>
</table>
<br>

<%= button_to "Add new category", new_category_path, method: "get"%>

app/views/categories/new.html.erb
<h3>New Category</h3>

<%= render "form"%>

<footer>

 <%=button_to 'Back', categories_path, method: "get"%>

</footer>

app/views/categories/show.html.erb
<h2><%=@category.title%></h2>
<table>
<% @category.articles.sort_by(&:created_at).each do |article| %>
<tr>
  <td>
   <%= link_to article.title, category_article_path(@category, article)%>
 </td>
 <td><%= link_to "Edit", edit_category_article_path(article.category, article)%></td>
  <td><%= button_to "Delete", category_article_path(@category, article), method: :delete %></td>
 </tr>
<% end %>
</table>

<br>

<%= button_to "Add new article", new_category_article_path(@category, @article), method: "get"%>
<br>

<footer>

 <%=button_to 'Back', categories_path, method: "get"%>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Morgan's List</h1>
    <hr>
  </header>

<%= yield %>


</body>
</html>